spring:
  application:
    name: alim-service
  redis:
    host: localhost
    port: 6379
    password: StrongPassword22!

server:
  port: 8082

aws:
  region: us-east-1
  sqs:
    endpoint-url: http://localhost:4566
    queue-url: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/your-queue-name