spring:
  application:
    name: alim-service
  datasource:
    # 본인 mysql url, username, password 설정하시면 됩니다!!
    url: jdbc:mysql://127.0.0.1:3307/dee-facto?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 5000
      maximum-pool-size: 10  # 추가: 커넥션 풀 크기 설정

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC  # 타임존 설정 추가
  redis:
    host: localhost
    port: 6379
    password: StrongPassword22!

server:
  port: 8082

aws:
  region: us-east-1
  sqs:
    endpoint-url: http://localhost:4566
    queue-url: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/your-queue-name